# Generated by Django 4.2.27 on 2026-01-08 04:44

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='姓名/昵称')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系方式')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='地址/档口')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='净头寸(正收负付)')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zencode', models.CharField(editable=False, max_length=20, unique=True, verbose_name='ZenCode唯一码')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称(自动生成)')),
                ('category', models.CharField(choices=[('ZJ', '整机'), ('SJ', '散件'), ('XS', '显示器'), ('ZX', '杂项')], max_length=2, verbose_name='分类')),
                ('cpu', models.CharField(blank=True, max_length=50, verbose_name='CPU')),
                ('gpu', models.CharField(blank=True, max_length=50, verbose_name='显卡(无则填核显)')),
                ('ram', models.CharField(blank=True, max_length=50, verbose_name='内存')),
                ('disk', models.CharField(blank=True, max_length=50, verbose_name='硬盘')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='备注')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='入库成本')),
                ('peer_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='同行底价')),
                ('retail_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='零售指导价')),
                ('status', models.CharField(choices=[('IN_STOCK', '在库'), ('RENTED', '在租'), ('SOLD', '已售'), ('REPAIR', '维修/报废')], default='IN_STOCK', max_length=10, verbose_name='状态')),
                ('image', models.ImageField(blank=True, null=True, upload_to='%Y/%m/', verbose_name='鉴得图')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='起租日')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='周期租金')),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='押金')),
                ('initial_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='出库时价值')),
                ('is_active', models.BooleanField(default=True, verbose_name='租赁中')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contact', verbose_name='客户')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='租赁设备')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', '管理员'), ('FINANCE', '财务/店长'), ('SALES', '销售/技术')], default='SALES', max_length=10, verbose_name='角色')),
                ('initials', models.CharField(default='XX', max_length=5, verbose_name='姓名首字母(用于ZenCode)')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
