# Generated by Django 4.2.27 on 2026-01-15 04:15

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', '👑 管理员'), ('FINANCE', '💰 财务'), ('SALES', '👤 销售')], default='SALES', max_length=10, verbose_name='角色')),
                ('initials', models.CharField(default='XX', max_length=5, verbose_name='头像字符')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': '员工账号',
                'verbose_name_plural': '员工账号',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CapitalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='账户名称')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='期初余额')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='当前余额')),
            ],
            options={
                'verbose_name': '资金账户',
                'verbose_name_plural': '资金账户',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='地址/档口')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='余额')),
            ],
            options={
                'verbose_name': '客户/供应商',
                'verbose_name_plural': '客户/供应商',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zencode', models.CharField(blank=True, max_length=20, verbose_name='编码')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('category', models.CharField(choices=[('ZJ', '💻 电脑主机'), ('PH', '📱 手机'), ('TB', '📟 平板'), ('XS', '📺 显示器'), ('SJ', '🔩 散件'), ('ZX', '📦 杂项')], max_length=2, verbose_name='分类')),
                ('cpu', models.CharField(blank=True, max_length=50, verbose_name='CPU/品牌')),
                ('gpu', models.CharField(blank=True, max_length=50, verbose_name='显卡/颜色')),
                ('ram', models.CharField(blank=True, max_length=50, verbose_name='内存/型号')),
                ('disk', models.CharField(blank=True, max_length=50, verbose_name='硬盘/容量')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='备注')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='参考成本')),
                ('peer_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='同行底价')),
                ('retail_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='零售指导')),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='实际成交价')),
                ('status', models.CharField(choices=[('IN_STOCK', '在库'), ('RENTED', '在租'), ('TRANSIT', '中转/外借'), ('SOLD', '已售'), ('REPAIR', '维修')], default='IN_STOCK', max_length=10, verbose_name='整体状态')),
                ('image', models.ImageField(blank=True, null=True, upload_to='%Y/%m/', verbose_name='图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
            ],
            options={
                'verbose_name': '📂 商品档案(SPU)',
                'verbose_name_plural': '📂 商品档案(SPU)',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='公司名称')),
                ('owner_name', models.CharField(max_length=50, verbose_name='负责人')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='登录手机号')),
                ('is_active', models.BooleanField(default=True, verbose_name='状态(审核)')),
                ('account_limit', models.IntegerField(default=5, verbose_name='最大子账户数')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='到期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '🏢 租户管理',
                'verbose_name_plural': '🏢 租户管理',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('type', models.CharField(choices=[('SALE', '销售收入'), ('RENT', '租金/押金'), ('BUY', '采购支出'), ('OTHER', '其他')], max_length=10, verbose_name='类型')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.capitalaccount', verbose_name='账户')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.contact', verbose_name='关联方')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='经手人')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product', verbose_name='商品')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '财务流水',
                'verbose_name_plural': '财务流水',
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=100, verbose_name='序列号/IMEI')),
                ('real_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='真实入库价')),
                ('status', models.CharField(choices=[('IN_STOCK', '✅ 在库'), ('RENTED', '🔄 在租'), ('SOLD', '💰 已售'), ('BAD', '🚫 报废')], default='IN_STOCK', max_length=20, verbose_name='当前状态')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='单机备注')),
                ('in_time', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='core.product', verbose_name='所属商品')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contact', verbose_name='供应商')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '📦 库存实物(SKU)',
                'verbose_name_plural': '📦 库存实物(SKU)',
                'unique_together': {('tenant', 'sn')},
            },
        ),
        migrations.CreateModel(
            name='SerialNumberFactory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=100, verbose_name='序列号/IMEI')),
                ('status', models.CharField(default='normal', max_length=20, verbose_name='状态')),
                ('src_type', models.CharField(default='import', max_length=20, verbose_name='来源')),
                ('check_result', models.TextField(blank=True, null=True, verbose_name='检测结果')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '🏭 序列号工厂',
                'verbose_name_plural': '🏭 序列号工厂',
            },
        ),
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='起租日')),
                ('duration', models.IntegerField(default=1, verbose_name='租期(月)')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='归还日')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='押金')),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='租金')),
                ('depreciation_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='月折旧')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总额')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已付')),
                ('expected_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='毛利')),
                ('is_active', models.BooleanField(default=True, verbose_name='进行中')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contact', verbose_name='客户')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='经手人')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='租赁设备')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.stockitem', verbose_name='具体序列号')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '租赁合同',
                'verbose_name_plural': '租赁合同',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='所属租户'),
        ),
        migrations.AddField(
            model_name='contact',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='所属租户'),
        ),
        migrations.AddField(
            model_name='capitalaccount',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='所属租户'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
