# Generated by Django 4.2.27 on 2026-01-08 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='成交价'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='净头寸'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='initials',
            field=models.CharField(default='XX', max_length=5, verbose_name='姓名首字母'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gpu',
            field=models.CharField(blank=True, max_length=50, verbose_name='显卡'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='商品名称(自动生成)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='zencode',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='ZenCode唯一码'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('type', models.CharField(choices=[('SALE', '销售收入'), ('RENT', '租金收入'), ('DEPOSIT', '押金收取'), ('REFUND', '退款/支出'), ('BUY', '采购支出')], max_length=10, verbose_name='类型')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contact', verbose_name='往来对象')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='经手人')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product', verbose_name='关联商品')),
            ],
        ),
    ]
