# Generated by Django 4.2.27 on 2026-01-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='need_sn',
            field=models.BooleanField(default=False, verbose_name='必须序列号'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='status',
            field=models.CharField(choices=[('IN_STOCK', '✅ 在库'), ('RENTED', '🔄 在租'), ('SOLD', '💰 已售'), ('BAD', '🚫 报废'), ('PENDING', '⏳ 待入库')], default='IN_STOCK', max_length=20, verbose_name='当前状态'),
        ),
    ]
