# Generated by Django 4.2.27 on 2026-01-09 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_capitalaccount_alter_contact_balance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capitalaccount',
            options={'verbose_name': '资金账户', 'verbose_name_plural': '资金账户'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': '客户/供应商档案', 'verbose_name_plural': '客户/供应商档案'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': '员工账号', 'verbose_name_plural': '员工账号'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '库存商品', 'verbose_name_plural': '库存商品'},
        ),
        migrations.AlterModelOptions(
            name='rentalcontract',
            options={'verbose_name': '租赁合同', 'verbose_name_plural': '租赁合同'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': '财务流水', 'verbose_name_plural': '财务流水'},
        ),
        migrations.RemoveField(
            model_name='rentalcontract',
            name='rent_amount',
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='depreciation_monthly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='月折旧估算'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='归还日'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='rent_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='租金单价'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='rent_strategy',
            field=models.CharField(choices=[('DAILY', '日租'), ('MONTHLY', '月租')], default='MONTHLY', max_length=10, verbose_name='计费方式'),
        ),
        migrations.AlterField(
            model_name='capitalaccount',
            name='name',
            field=models.CharField(help_text='如: 支付宝, 微信', max_length=50, verbose_name='账户名称'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='应收/应付余额'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='姓名/昵称'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='initials',
            field=models.CharField(default='XX', help_text='用于生成单号，如 WZ', max_length=5, verbose_name='姓名首字母'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ZJ', '整机'), ('SJ', '散件'), ('XS', '显示器'), ('ZX', '杂项')], max_length=2, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='入库成本'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cpu',
            field=models.CharField(blank=True, max_length=50, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='入库时间'),
        ),
        migrations.AlterField(
            model_name='product',
            name='disk',
            field=models.CharField(blank=True, max_length=50, verbose_name='硬盘'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gpu',
            field=models.CharField(blank=True, max_length=50, verbose_name='显卡'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='product',
            name='note',
            field=models.CharField(blank=True, max_length=100, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='product',
            name='peer_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='同行底价'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.CharField(blank=True, max_length=50, verbose_name='内存'),
        ),
        migrations.AlterField(
            model_name='product',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='零售指导'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='实际成交价'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('IN_STOCK', '在库'), ('RENTED', '在租'), ('SOLD', '已售'), ('REPAIR', '维修')], default='IN_STOCK', max_length=10, verbose_name='当前状态'),
        ),
        migrations.AlterField(
            model_name='product',
            name='zencode',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='ZenCode编码'),
        ),
        migrations.AlterField(
            model_name='rentalcontract',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contact', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='rentalcontract',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实收押金'),
        ),
        migrations.AlterField(
            model_name='rentalcontract',
            name='initial_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='出库价值'),
        ),
        migrations.AlterField(
            model_name='rentalcontract',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='租赁中'),
        ),
        migrations.AlterField(
            model_name='rentalcontract',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='设备'),
        ),
        migrations.AlterField(
            model_name='rentalcontract',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='起租日'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.contact', verbose_name='关联方'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='经手人'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product', verbose_name='关联商品'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='remark',
            field=models.CharField(blank=True, max_length=200, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('SALE', '销售收入'), ('RENT', '租金/押金'), ('BUY', '采购支出'), ('OTHER', '其他')], max_length=10, verbose_name='类型'),
        ),
    ]
