# Generated by Django 4.2.27 on 2026-01-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_capitalaccount_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalcontract',
            name='duration',
            field=models.IntegerField(default=1, verbose_name='租期(月)'),
        ),
    ]
