# Generated by Django 4.2.27 on 2026-01-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rentalcontract_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalcontract',
            name='expected_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='预估毛利'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已付租金'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='合同总额'),
        ),
    ]
