# Generated by Django 4.2.27 on 2026-01-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rentalcontract_expected_profit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('IN_STOCK', '在库'), ('RENTED', '在租'), ('TRANSIT', '中转/外借'), ('SOLD', '已售'), ('REPAIR', '维修')], default='IN_STOCK', max_length=10, verbose_name='当前状态'),
        ),
    ]
