# Generated by Django 4.2.27 on 2026-01-12 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalcontract',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='经手人'),
        ),
    ]
