# Generated by Django 4.2.27 on 2026-01-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rentalcontract_operator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': '客户/供应商', 'verbose_name_plural': '客户/供应商'},
        ),
        migrations.RemoveField(
            model_name='rentalcontract',
            name='initial_value',
        ),
        migrations.RemoveField(
            model_name='rentalcontract',
            name='rent_strategy',
        ),
        migrations.AlterField(
            model_name='capitalaccount',
            name='name',
            field=models.CharField(max_length=50, verbose_name='账户名称'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='initials',
            field=models.CharField(default='XX', max_length=5, verbose_name='姓名首字母'),
        ),
    ]
